name: Simple panini

on:
  #schedule:
  #  - cron: '0 * * * *'
  workflow_dispatch:

jobs:
   test:
       runs-on: ubuntu-latest
       steps:
           - name: Premier log de suivi
             run: echo "Première étape"
